#!/bin/bash

help()
{
  cat "doc/$(basename "$0").help"
}

removed_elements=(Alarms Android DCIM Download Movies Music Notifications Pictures Podcasts Ringtones)

case "$1" in
  -h \
  | --help)
    help
    ;;
  -l \
  | --list)
    echo ${removed_elements[@]}
    ;;
  "")
    echo "missing PATH operand"
    echo "Try 'rmtvjunk --help' for more information."
    ;;
  *)
    path="$(realpath --canonicalize-missing "$1")"

    if ! [[ -e $path ]]
    then
      echo "'$1' path does not exists"
      exit 1
    fi

    for item in ${removed_elements[@]}
    do
      rm -r "$path/$item"
    done
    ;;
esac