#!/bin/bash

help()
{
  echo "usage: rmtvjunk PATH"
  echo "   or: rmtvjunk -l | --list"
  echo ""
  echo "Removes junk files created by the TV's operating system."
  echo ""
  echo "options:"
  echo "  -h, --help: displays help"
  echo "  -l, --list: lists the directories, files to be removed."
}

removed_elements=(Alarms Android DCIM Download Movies Music Notifications Pictures Podcasts Ringtones)

case "$1" in
  -h \
  | --help)
    help
    ;;
  -l \
  | --list)
    echo ${removed_elements[@]}
    ;;
  "")
    echo "missing PATH operand"
    echo "Try 'rmtvjunk --help' for more information."
    ;;
  *)
    path="$(realpath --canonicalize-missing "$1")"

    if ! [[ -e $path ]]
    then
      echo "'$1' path does not exists"
      exit 1
    fi

    for item in ${removed_elements[@]}
    do
      rm -r "$path/$item"
    done
    ;;
esac